apiVersion: v1
kind: ConfigMap
metadata:
  name: coworking-postgresql
data:
  DB_HOST: "postgresql-service.default.svc.cluster.local"
  DB_PORT: "5432"
  DB_USERNAME: "postgres"
  DB_NAME: "postgres"
---
apiVersion: v1
kind: Secret
metadata:
  name: coworking-secret
type: Opaque
data:
  DB_PASSWORD: cG9zdGdyZXM=